### PR TITLE
Small fix to vectorize for python 2/3 compatibility

### PR DESCRIPTION
**Pull request by wronk**

### CODE REVIEW

**Comment by drewbo** [comment]
@wronk can you just add a small write-up on the change and how it affects performance? I switched the reviewer to @matthewhanson as he wrote this script

**Comment by matthewhanson** [comment]
This looks fine to me. I generally avoid using six and just target Python 3 these days, especially for end use scripts. For libraries that may be included as dependencies I understand sometimes six is required, although I usually try to rewrite the code in a version agnostic way if possible.

That being said, I'm overall okay with this, although also interested in the performance hit.

**Comment by wronk** [comment]
I'll try to implement a better version agnostic fix when I get a second. I can probably do it without six

**Comment by wronk** [comment]
@matthewhanson, this now works with 2 and 3 w/out `six`. No performance hit either

**Pull request merged**
