### PR TITLE
Share experiments

### LINKED ISSUE #7: Release of trained caffemodel?
I'm looking to use this as a pretraining step for fine-tuning later on. Would it be possible to have the pre-trained caffemodel that you've created? 

I'm working on a similar task, and I believe transferring weights from ImageNet or Pascal for example to this overhead imagery case may be problematic in more difficult situations. So using a pretrained network in the correct domain of overhead imagery would improve performance significantly I believe. Thanks.

### PR DESCRIPTION
**Pull request by anandthakker**
Closes #7

### CODE REVIEW

**Comment by anandthakker** [comment]
Actually since this is all just content, self-merging

**Comment by nk-dev0** [comment]
Thank you! Will report back/release something with some of my own findings

**Comment by nk-dev0** [comment]
Is it possible to release the segnet_train.prototxt files you've used for each of the experiments as well? I'm running into some compatibility issues when finetuning with your caffemodels using my own segnet_train.prototxt's. I'm also using a segnet caffe implementation with the most recent caffe updates (https://github.com/jimchenhub/new-caffe-segnet).

**Comment by anandthakker** [comment]
@nkrall yes, definitely -- this was an unfortunate oversight when I first copied the files over.  It's on our todo list to get those files copied over!

**Comment by nk-dev0** [comment]
Any updates?

**Comment by nk-dev0** [comment]
Hi just checking back to see if you could please release prototxt files used to train caffemodels in share-experiments.

**Pull request merged**
